### PR TITLE
Vue UI

### PR DESCRIPTION
**Pull request by jost-s**
Replaces existing Svelte UI with Vue UI

### CODE REVIEW

**Comment by bierlingm** [comment]
Looks good to me. @zippy, @artbrock, any further comments / questions?

**Comment by jost-s** [comment]
Yeah, it's coming together. I've put together a basic architecture to be expanded upon.

What doesn't work yet is the dynamic passing of the AppWebsocket's port from environment variable to the Vue app. i've [submitted a ticket for it](https://github.com/vitejs/vite/issues/6626) and will think of a workaround.

**Comment by jost-s** [comment]
- passing on the App ws port from env var works
- fixed building for production

**Review by harlantwood — APPROVED** [review]
LGTM. I think we should merge asap so others can build of this in the hackalong.

**Pull request merged**
