### PR TITLE
Feat/humanize timestamps

### PR DESCRIPTION
**Pull request by mattyg**

### CODE REVIEW

**Comment by jost-s** [comment]
I forgot to mention this in the previous PR: Please add changes to the changelog under "Unreleased".

**Comment by jost-s** [comment]
And you can also tick the box for "search for hashtag/cashtag" in the specs.

**Comment by mattyg** [comment]
> I forgot to mention this in the previous PR: Please add changes to the changelog under "Unreleased".
> And you can also tick the box for "search for hashtag/cashtag" in the specs.

all set @jost-s

**Review by jost-s — CHANGES_REQUESTED** [review]
6 MB only for this is quite heavy on the package. [day.js](https://www.npmjs.com/package/dayjs) is much more lightweight and provides a similar API. Please replace the package.

I'm fully occupied with Holochain work until end of January and therefore won't be quick to review your PRs. They're nevertheless much appreciated!

**Comment by mattyg** [comment]
> 6 MB only for this is quite heavy on the package. [day.js](https://www.npmjs.com/package/dayjs) is much more lightweight and provides a similar API. Please replace the package.

I think you mean 6 KB? Still looks like date-fns is a bit heavier than dayjs. I swapped them out.

> I'm fully occupied with Holochain work until end of January and therefore won't be quick to review your PRs. They're nevertheless much appreciated!

Sounds good -- let me know if there's more from the backlog I can take on and queue up a bunch of PRs for you to look at later.

**Comment by jost-s** [comment]
> I think you mean 6 KB? Still looks like date-fns is a bit heavier than dayjs. I swapped them out.

No, I meant 6 MB unpacked 
image

Cool, I'll post more items on Discord promptly. Thank you for the contributions!

**Review by jost-s — APPROVED** [review]

**Comment by mattyg** [comment]
> > I think you mean 6 KB? Still looks like date-fns is a bit heavier than dayjs. I swapped them out.
> 
> No, I meant 6 MB unpacked image

Huh, I think that's the size of the source code? [Bundlephobia](https://bundlephobia.com/package/date-fns@2.29.3) shows 160KB, but then it get's tree-shaken so we would only come out to a few KB to import that one function. Anyway doesn't matter dayjs is clearly preferable!

 
> Cool, I'll post more items on Discord promptly. Thank you for the contributions!

:+1:

**Comment by jost-s** [comment]
Alright, good that you checked. Yes, we go with dayjs for the time being and should we need something else in the future we can replace it.

**Pull request merged**
